name: Sample github workflow
on:
  push:
    branches:
      - 'feature/**'
      - 'releases/*'
      
  workflow_dispatch:
    inputs:
      env:
        description: enter the env
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod
        - stage
        - qa
  
