name: docker build

on:
 push:

jobs:
 build:
  runs-on: ubuntu-latest
  env:
   DOCKER_IMAGE: karthikamn/flask-api-python-app

  steps:
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}




  
   

   
  
       
  
    -
      
      
      
      
       
       
      
   
        
          
       
       
       
        
      
