name: docker build

on:
 push:

jobs:
 build:
  runs-on: ubuntu-latest
  env:
   DOCKER_IMAGE: sonalivarshney/sampleapp

  steps:
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: |
        docker build -t myapp .
        docker tag myapp:latest ${DOCKER_IMAGE}:${{github.ref}}
        docker push ${DOCKER_IMAGE}:${{github.ref}}







      




  
   

   
  
       
  
    -
      
      
      
      
       
       
      
   
        
          
       
       
       
        
      
