name: Sample github workflow
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: first job
       uses: actions/Bayer_Training@main
       with:
         who-to-greet: 'Mona the Octocat'
    
      
        
  
