name: environment and download the artifact
on:
  push:

env:
    age: 15
jobs:

  deployonDev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
     - name: Print secrets and var of dev env
       run: |
         echo "Sample var value for dev env is ${{vars.name}}"
         echo "Sample secret value for dev env is ${{secrets.passw}}"
         echo "Sample secret value for env var is ${{env.age}}"
    
  deployonQA:
    runs-on: ubuntu-latest
    environment: QA
    steps:
     - name: Print secrets and var of QA env
       run: |
         echo "Sample var value for qa env is ${{vars.name}}"
         echo "Sample secret value for qa env is ${{secrets.passw}}"
         echo "Sample secret value for env var is ${{env.age}}"

  deployonProd:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
     - name: Print secrets and var of prod env
       run: |
         echo "Sample var value for prod env is ${{vars.name}}"
         echo "Sample secret value for prod env is ${{secrets.passw}}"
         echo "Sample secret value for env var is ${{env.age}}"

