name: environment and download the artifact
on:
  workflow_dispatch:
    inputs:
      env:
        description: enter the env
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod
        - stage
        - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: first job
       run: |
            echo "github.actor is ${{github.actor}}"
            echo " github.event is ${{github.event}}"
            echo "github.ref is ${{github.ref}}"
            echo "github.ref_name is ${{github.ref_name}}"
            echo "github.repository is ${{github.repository}}" 
