name: github outputs
on:
  push:

jobs:
  build:
    outputs:
      exportingoutput: ${{steps.test.outputs.age}}
    runs-on: ubuntu-latest

    steps:
     - name: first step
       id: test
       run: echo "age=10" >> "$GITHUB_OUTPUT"


     - name: second step
       run: echo "Hi"

     - name: third step
       run: echo "output value is ${{steps.test.outputs.age}}"
       
        


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
     - name: access output produced by first job    
       run: echo "output produced by first job is ${{needs.build.outputs.exportingoutput}}"

      
        
  
