name: Sample github workflow
on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform

    steps:
     - name: Checkout
       uses: actions/checkout@v5.0.0
     
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
       with:
          terraform_version: 1.5.0
     
     - name: "Configure AWS Credentials"
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-region: us-east-1
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}

     - name: init
       run: terraform init
       
     - name: validate
       run: terraform validate
  
     - name: apply
       run: terraform apply -auto-approve
      
      
        
